(async()=>{
 'use strict';
 const D=Canvastect.Domain,V=Canvastect.Views,DB=Canvastect.Storage,E=Canvastect.Exporters;
 const $=s=>document.querySelector(s),modal=$('#modal');
 const S={doc:null,fid:null,bid:null,route:'source',view:'timeline',search:'',time:0,px:null,viewport:800,snap:0,playing:false,sidebar:false,month:new Date().toISOString().slice(0,7),saveState:'',undo:[],redo:[],busy:false,formDirty:false};
 const toast=t=>{$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(S.toast);S.toast=setTimeout(()=>$('#toast').classList.remove('show'),4200);};
 const f=()=>S.doc?.fichas.find(x=>x.id===S.fid);
 const b=()=>f()?.blocks.find(x=>x.id===S.bid);
 const close=()=>modal.close();
 const show=html=>{modal.innerHTML=V.btn('close','×','modal-close','aria-label="Cerrar diálogo"')+html;if(!modal.open)modal.showModal();};
 const safe=fn=>async(...a)=>{try{await fn(...a);}catch(e){console.error(e);toast(e.message||String(e));}};
 function selectFicha(id){S.fid=id;S.bid=null;S.px=null;S.time=0;S.route=D.routes(f())[0]||'source';S.sidebar=false;S.view='timeline';S.formDirty=false;render();}
 function ensure(){if(!S.doc)return;if(!f())S.fid=S.doc.fichas[0]?.id||null;if(f()&&!D.routes(f()).includes(S.route))S.route='source';if(!b())S.bid=null;}
 function render(){ensure();const scroll=$('#timeline-scroll');const sx=scroll?.scrollLeft||0;$('#app').innerHTML=V.shell(S);const el=$('#timeline-scroll');if(el){S.viewport=el.clientWidth;el.innerHTML=V.timeline(S,f());el.scrollLeft=sx;}if(S.view==='history'&&S.doc)loadHistory();}
 async function commit(reason,fn){if(S.busy)throw Error('Espera a que termine el guardado.');if(!S.doc)throw Error('Crea o importa un proyecto primero.');S.busy=true;try{const prev=D.clone(S.doc),next=D.clone(S.doc);fn(next);D.validate(next);D.touch(next);await DB.save(next,prev,reason);S.undo.push(prev);if(S.undo.length>15)S.undo.shift();S.redo=[];S.doc=next;S.saveState='Guardado local · '+new Date().toLocaleTimeString();S.formDirty=false;render();}finally{S.busy=false;}}
 async function adopt(doc,why='Importación'){D.validate(doc);const previous=await DB.get(doc.projectId);if(previous&&JSON.stringify(previous)!==JSON.stringify(doc))D.touch(doc);await DB.save(doc,previous,why);S.doc=doc;S.fid=doc.fichas[0]?.id;S.bid=null;S.route='source';S.undo=[];S.redo=[];S.saveState='Guardado en este dispositivo';S.formDirty=false;try{localStorage.setItem('canvastect-last',doc.projectId);}catch{}render();}
 function pick(accept,cb){const input=$('#file-input');input.accept=accept;input.value='';input.onchange=safe(async()=>{if(input.files[0])await cb(input.files[0]);});input.click();}
 async function importFile(file){if(file.size>80*1024*1024)throw Error('Límite de entrada: 80 MB.');const doc=Canvastect.Importers.text(await file.text());const same=await DB.get(doc.projectId);show(`<h2>Revisar importación</h2><p>${V.esc(doc.title)}</p><div class="metric-row"><b>${doc.fichas.length} fichas</b><b>${doc.fichas.reduce((n,f)=>n+f.blocks.length,0)} elementos</b></div><p>${V.esc((doc.importWarnings||[]).join('\n'))}</p><p>${same?'Este ID ya existe. La actualización conserva una copia anterior en Historial. En esta versión se reemplaza el documento completo; no se fusionan campos automáticamente.':'Se creará un proyecto independiente.'}</p><div class="actions">${V.btn('accept-import',same?'Actualizar y conservar anterior':'Importar proyecto','primary')}${V.btn('import-copy','Crear copia independiente')}</div>`);S.pendingImport=doc;}
 async function saveBlock(){const form=$('#block-form');if(!form||!b())return;const data=Object.fromEntries(new FormData(form));const fid=S.fid,bid=S.bid,r=S.route;await commit('Editar elemento',doc=>{const ff=doc.fichas.find(x=>x.id===fid);D.setTimes(ff,bid,r,Number(data.start),Number(data.end));const bb=ff.blocks.find(x=>x.id===bid);bb.label=data.label;bb.description=data.description;bb.instructions=data.instructions;bb.status=data.status;bb.displayText=data.text;bb.text=data.text;bb.prompts={...bb.prompts,noText:data.prompt};});}
 async function flush(){if(S.formDirty)await saveBlock();}
 async function loadHistory(){const id=S.doc.projectId;try{const rows=await DB.history(id);if(S.doc.projectId!==id||S.view!=='history')return;S.history=rows;$('#history-view').innerHTML=`<div class="eyebrow">VERSIONES DE ESTE DISPOSITIVO</div><h1>Tu trabajo tiene memoria.</h1><p>Exportar una versión anterior no cambia la actual. Restaurar crea una nueva revisión.</p><div class="history-row"><div><b>Versión actual</b><p>${V.esc(S.doc.updatedAt)}</p></div>${V.btn('export-html','HTML')}${V.btn('export-txt','TXT')}</div>${rows.map((h,i)=>`<div class="history-row"><div><b>${V.esc(h.reason)}</b><p>${V.esc(new Date(h.at).toLocaleString())} · ${h.document.fichas.length} fichas</p></div>${V.btn('history-html','HTML','',`data-index="${i}"`)}${V.btn('history-txt','TXT','',`data-index="${i}"`)}${V.btn('history-view','Ver datos','',`data-index="${i}"`)}${V.btn('restore','Restaurar','',`data-index="${i}"`)}</div>`).join('')||'<p>No hay revisiones anteriores todavía.</p>'}<p class="muted">Historial local en IndexedDB. Exporta respaldos: borrar los datos del navegador también elimina estas revisiones. No se purgan automáticamente.</p>`;}catch(e){toast(e.message);}}
 async function copy(text){try{await navigator.clipboard.writeText(text);toast('Copiado');}catch{show('<h2>Texto para copiar</h2><textarea rows="15" readonly>'+V.esc(text)+'</textarea>');}}
 function editFicha(){const ff=f();show(`<h2>Ficha editorial</h2><form id="ficha-form">${V.field('Título','title',ff.title)}${V.field('Hook','hook',ff.copy?.hook||'',true)}${V.field('Desarrollo','body',ff.copy?.body||ff.copy?.fullCopy||'',true)}${V.field('CTA','cta',ff.copy?.cta||'',true)}${V.field('Fecha de publicación','date',ff.scheduledDate||'',false,'date')}<div class="two"><label>Madurez<select name="maturity"><option ${ff.maturity==='beta'?'selected':''}>beta</option><option ${ff.maturity==='alfa'?'selected':''}>alfa</option></select></label><label>Producción<select name="status">${['draft','in_production','ready_for_review','confirmed_publish','published'].map(x=>`<option ${ff.status===x?'selected':''}>${x}</option>`).join('')}</select></label></div>${V.field('Notas','note',ff.note||'',true)}<p class="muted">${V.esc(D.missing(ff).join(' · '))}. Marcar alfa es una decisión editorial; no genera ni verifica los recursos automáticamente.</p><button class="primary">Guardar ficha</button></form>`);}
 function addBlock(parentId=null){show(`<h2>${parentId?'Imagen dentro del XR':'Nuevo elemento'}</h2><form id="add-form" data-parent="${V.esc(parentId||'')}"><label>Tipo<select name="lane">${(parentId?D.tracks.filter(t=>t[0]==='T3'):D.tracks).map(([v,l])=>`<option value="${v}">${v} · ${l}</option>`).join('')}</select></label>${V.field('Nombre','label','Nuevo elemento')}<div class="two">${V.field('Inicio','start',parentId?D.timing(b(),S.route).start:S.time,false,'number')}${V.field('Duración (s)','duration',parentId?D.timing(b(),S.route).end-D.timing(b(),S.route).start:2,false,'number')}</div><button class="primary">Crear y abrir inspector</button></form>`);}
 async function exportNow(format){await flush();await E.exportDoc(S.doc,format);toast('Exportación preparada con el documento actual');}
 document.addEventListener('click',safe(async ev=>{
  const piece=ev.target.closest('[data-ficha]');if(piece){await flush();selectFicha(piece.dataset.ficha);return;}
  const el=ev.target.closest('[data-block]');if(el&&!S.preventClick){await flush();S.bid=el.dataset.block;const bb=D.visibleEvents(f(),S.route).find(x=>x.id===S.bid);if(bb)S.time=bb.start;render();return;}
  const button=ev.target.closest('[data-action]');if(!button)return;const a=button.dataset.action;
  if(a==='close'){close();return;}if(a==='sidebar'){S.sidebar=!S.sidebar;$('#app .workspace').classList.toggle('show-library',S.sidebar);return;}
  if(a==='import'){await flush();pick('.html,.txt,.json',importFile);return;}
  if(a==='new-project'){show('<h2>Nuevo proyecto</h2><form id="project-form">'+V.field('Nombre','title','Mi proyecto')+'<button class="primary">Crear</button></form>');return;}
  if(a==='projects'){await flush();const docs=await DB.list();S.projects=docs;show('<h2>Proyectos de este dispositivo</h2>'+docs.map((x,i)=>V.btn('open-project',V.esc(x.title),'project-option',`data-index="${i}"`)).join('')+V.btn('new-project','+ Nuevo proyecto','primary'));return;}
  if(a==='open-project'){close();await adopt(S.projects[Number(button.dataset.index)],'Abrir proyecto');return;}
  if(a==='accept-import'||a==='import-copy'){const doc=S.pendingImport;if(a==='import-copy'){doc.projectId=D.id();doc.revisionId=D.id();}await adopt(doc,'Antes de importar actualización');close();toast('Importación completa');return;}
  if(a==='new-ficha'){if(!S.doc)await adopt(D.empty());show(`<h2>Nueva ficha</h2><form id="new-ficha-form">${V.field('Título','title','Mi contenido')}<label>Formato<select name="type">${['intro','vertical','horizontal','carousel','thread','note','quote','pdf','full_episode'].map(x=>'<option>'+x+'</option>').join('')}</select></label><button class="primary">Crear ficha</button></form>`);return;}
  if(!S.doc)throw Error('Importa o crea un proyecto primero.');
  if(a==='view'){await flush();S.view=button.dataset.view;S.playing=false;render();return;}
  if(a==='export'){await flush();show(`<h2>Tu lienzo, completo.</h2><p>Se exportan ${S.doc.fichas.length} fichas con el estado actual. El HTML incluye este mismo editor y puede abrirse sin servidor.</p><div class="actions">${V.btn('export-html','Descargar lienzo HTML','primary')}${V.btn('export-txt','Descargar TXT completo')}${V.btn('export-source','Fuente original')}</div><p class="muted">El TXT contiene JSON íntegro con encabezado. No se publica nada en GitHub al descargar. El máster de video abierto para consulta no se incluye.</p>`);return;}
  if(a==='export-html'||a==='export-txt'){await exportNow(a==='export-html'?'html':'txt');return;}
  if(a==='export-source'){await E.download('fuente_original.json',JSON.stringify(S.doc.sourcePayload||{},null,2));return;}
  if(a==='edit-ficha'){await flush();editFicha();return;}
  if(a==='close-inspector'){await flush();S.bid=null;render();return;}
  if(a==='add-block'||a==='add-child'){await flush();addBlock(a==='add-child'?S.bid:null);return;}
  if(a==='delete-block'){const target=b();const n=f().blocks.filter(x=>x.parentId===S.bid).length;show(`<h2>Eliminar ${V.esc(target.label)}</h2><p>Se eliminará el elemento y sus descendientes (${n} hijos directos). La versión anterior quedará en Historial.</p>${V.btn('confirm-delete','Eliminar','danger')}`);return;}
  if(a==='confirm-delete'){const bid=S.bid;await commit('Eliminar elemento y descendientes',doc=>{const ff=doc.fichas.find(x=>x.id===S.fid),ids=new Set([bid]);let again=true;while(again){again=false;for(const x of ff.blocks)if(ids.has(x.parentId)&&!ids.has(x.id)){ids.add(x.id);again=true;}}ff.blocks=ff.blocks.filter(x=>!ids.has(x.id));});S.bid=null;close();render();return;}
  if(a==='copy-block'){await flush();await copy(JSON.stringify(b(),null,2));return;}
  if(a==='image'){await flush();pick('image/png,image/jpeg,image/webp',async file=>{if(file.size>8*1024*1024)throw Error('Máximo 8 MB por imagen en esta versión.');if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('Usa PNG/JPEG/WebP');const data=await new Promise((resolve,reject)=>{const r=new FileReader;r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});await commit('Vincular imagen',doc=>{doc.fichas.find(x=>x.id===S.fid).blocks.find(x=>x.id===S.bid).imageData=data;});});return;}
  if(a==='master'){pick('video/*',file=>{if(S.masterUrl)URL.revokeObjectURL(S.masterUrl);S.masterUrl=URL.createObjectURL(file);show('<h2>Máster · consulta de fuente</h2><video controls style="width:100%;max-height:65vh" src="'+V.esc(S.masterUrl)+'"></video><p>Archivo de sesión. Consulta libre; no hay sincronización automática montaje/fuente en esta versión.</p>');});return;}
  if(a==='fit'||a.startsWith('zoom-')){await flush();const px=Number($('.timeline')?.dataset.px)||20;S.px=a==='fit'?null:a==='zoom-in'?Math.min(400,px*1.6):Math.max(.01,px/1.6);render();return;}
  if(a==='play'){S.playing=!S.playing;render();return;}
  if(a==='undo'||a==='redo'){await flush();const stack=a==='undo'?S.undo:S.redo;if(!stack.length){toast('No hay operaciones');return;}const prev=S.doc,next=D.clone(stack.pop());(a==='undo'?S.redo:S.undo).push(D.clone(prev));D.touch(next);await DB.save(next,prev,a==='undo'?'Deshacer':'Rehacer');S.doc=next;render();return;}
  if(a==='prev-month'||a==='next-month'){const d=new Date(S.month+'-01T12:00:00');d.setMonth(d.getMonth()+(a==='next-month'?1:-1));S.month=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');render();return;}
  if(a.startsWith('history-')){const h=S.history[Number(button.dataset.index)];if(a==='history-view')show('<h2>'+V.esc(h.reason)+'</h2><pre>'+V.esc(JSON.stringify(h.document,null,2))+'</pre>');else await E.exportDoc(h.document,a==='history-html'?'html':'txt');return;}
  if(a==='restore'){S.restore=S.history[Number(button.dataset.index)].document;show('<h2>Restaurar como nueva revisión</h2><p>La versión actual se conservará antes de restaurar.</p>'+V.btn('confirm-restore','Restaurar','primary'));return;}
  if(a==='confirm-restore'){const next=D.clone(S.restore);D.touch(next);await DB.save(next,S.doc,'Antes de restaurar');S.doc=next;S.undo=[];S.redo=[];close();render();return;}
  if(a==='add-item'||a==='edit-item'){const x=a==='add-item'?{id:D.id(),title:'Nueva lámina',text:'',prompt:''}:f().items.find(x=>x.id===button.dataset.id);show(`<h2>Lámina / sección</h2><form id="item-form" data-id="${V.esc(x.id)}">${V.field('Título','title',x.title)}${V.field('Texto','text',x.text,true)}${V.field('Prompt visual','prompt',x.prompt,true)}<button class="primary">Guardar</button></form>`);return;}
  if(a==='copy-item'){await copy(JSON.stringify(f().items.find(x=>x.id===button.dataset.id),null,2));return;}
  if(['item-up','item-down','delete-item'].includes(a)){await commit('Editar orden de contenido',doc=>{const ff=doc.fichas.find(x=>x.id===S.fid),i=ff.items.findIndex(x=>x.id===button.dataset.id);if(a==='delete-item')ff.items.splice(i,1);else{const j=i+(a==='item-up'?-1:1);if(j>=0&&j<ff.items.length)[ff.items[i],ff.items[j]]=[ff.items[j],ff.items[i]];}});return;}
 }));
 document.addEventListener('submit',safe(async ev=>{ev.preventDefault();const form=ev.target,data=Object.fromEntries(new FormData(form));
  if(form.id==='block-form'){await saveBlock();toast('Elemento guardado');return;}
  if(form.id==='project-form'){await adopt(D.empty(data.title));close();return;}
  if(form.id==='new-ficha-form'){const n=D.newFicha(data.type);n.title=data.title;await commit('Crear ficha',doc=>doc.fichas.push(n));close();selectFicha(n.id);return;}
  if(form.id==='ficha-form'){await commit('Editar ficha',doc=>{const ff=doc.fichas.find(x=>x.id===S.fid);ff.title=data.title;ff.copy={...ff.copy,hook:data.hook,body:data.body,cta:data.cta,fullCopy:[data.hook,data.body,data.cta].filter(Boolean).join('\n\n')};ff.scheduledDate=data.date;ff.status=data.status;ff.maturity=data.maturity;ff.note=data.note;});close();return;}
  if(form.id==='add-form'){const start=Number(data.start),end=start+Number(data.duration),bid=D.id(),parent=form.dataset.parent||null;if(end<=start)throw Error('La duración debe ser positiva');await commit('Añadir elemento',doc=>{const ff=doc.fichas.find(x=>x.id===S.fid);ff.blocks.push(D.block({id:bid,laneId:data.lane,kind:D.kinds[data.lane],label:data.label,start,end,routes:[S.route],parentId:parent,status:'planned'}));});S.bid=bid;close();render();return;}
  if(form.id==='item-form'){await commit('Editar lámina',doc=>{const ff=doc.fichas.find(x=>x.id===S.fid),i=ff.items.findIndex(x=>x.id===form.dataset.id),x={...(ff.items[i]||{}),...data,id:form.dataset.id};if(i<0)ff.items.push(x);else ff.items[i]=x;});close();return;}
 }));
 document.addEventListener('input',ev=>{if(ev.target.closest('#block-form'))S.formDirty=true;if(ev.target.id==='search'){S.search=ev.target.value;const query=S.search.toLowerCase();document.querySelectorAll('.piece').forEach(el=>{el.hidden=!el.textContent.toLowerCase().includes(query);});}});
 document.addEventListener('change',safe(async ev=>{if(ev.target.id==='route'){await flush();S.route=ev.target.value;S.bid=null;S.time=0;S.px=null;render();}if(ev.target.id==='snap')S.snap=Number(ev.target.value);}));
 let drag=null;
 document.addEventListener('pointerdown',ev=>{
  const block=ev.target.closest('.block');if(!block){const ruler=ev.target.closest('[data-ruler]');if(ruler){const rect=ruler.getBoundingClientRect(),px=Number($('.timeline').dataset.px);S.time=Math.max(0,Math.min(D.duration(f(),S.route),(ev.clientX-rect.left-116)/px));updateClock();}return;}
  if(ev.button!==0||S.formDirty)return;
  if(ev.pointerType==='touch'&&S.bid!==block.dataset.block){S.bid=block.dataset.block;render();return;}
  const bb=D.visibleEvents(f(),S.route).find(x=>x.id===block.dataset.block);if(!bb)return;
  block.setPointerCapture(ev.pointerId);drag={id:bb.id,start:bb.start,end:bb.end,x:ev.clientX,px:Number($('.timeline').dataset.px),edge:ev.target.dataset.edge||'move',el:block,pointerId:ev.pointerId,changed:false};
 });
 document.addEventListener('pointermove',ev=>{if(!drag||ev.pointerId!==drag.pointerId)return;let delta=(ev.clientX-drag.x)/drag.px;if(S.snap)delta=Math.round(delta/S.snap)*S.snap;let start=drag.start,end=drag.end;if(drag.edge==='move'){start=Math.max(0,start+delta);end=start+drag.end-drag.start;}else if(drag.edge==='left')start=Math.max(0,Math.min(end-.001,start+delta));else end=Math.max(start+.001,end+delta);drag.next={start,end};drag.changed=Math.abs(ev.clientX-drag.x)>3;drag.el.style.left=116+start*drag.px+'px';drag.el.style.width=Math.max(1,(end-start)*drag.px)+'px';$('#clock').textContent=V.fmt(start)+' → '+V.fmt(end);});
 document.addEventListener('pointerup',safe(async ev=>{if(!drag||ev.pointerId!==drag.pointerId)return;const x=drag;drag=null;if(x.changed){S.preventClick=true;setTimeout(()=>S.preventClick=false,250);try{await commit('Mover / redimensionar elemento',doc=>D.setTimes(doc.fichas.find(f=>f.id===S.fid),x.id,S.route,x.next.start,x.next.end));S.bid=x.id;render();}catch(e){render();throw e;}}}));
 document.addEventListener('pointercancel',()=>{if(drag){drag=null;render();}});
 document.addEventListener('keydown',safe(async ev=>{if(ev.key==='Escape'&&drag){drag=null;render();}if(ev.target.matches('input,textarea,select')||ev.target.isContentEditable)return;if(ev.key==='Enter'&&ev.target.dataset.block){S.bid=ev.target.dataset.block;render();}if(S.view==='timeline'&&f()&&['ArrowLeft','ArrowRight'].includes(ev.key)){ev.preventDefault();S.time=Math.max(0,Math.min(D.duration(f(),S.route),S.time+(ev.key==='ArrowRight'?1:-1)));updateClock();}if(ev.key===' '&&S.view==='timeline'&&f()){ev.preventDefault();S.playing=!S.playing;render();}}));
 document.addEventListener('dragstart',ev=>{const x=ev.target.closest('[data-scheduled]');if(x)ev.dataTransfer.setData('text/plain',x.dataset.scheduled);});
 document.addEventListener('dragover',ev=>{if(ev.target.closest('[data-date]'))ev.preventDefault();});
 document.addEventListener('drop',safe(async ev=>{const day=ev.target.closest('[data-date]');if(!day)return;ev.preventDefault();const fid=ev.dataTransfer.getData('text/plain');if(!S.doc.fichas.some(f=>f.id===fid))return;await commit('Programar publicación',doc=>doc.fichas.find(f=>f.id===fid).scheduledDate=day.dataset.date);}));
 function updateClock(){if(!f()||!$('#clock'))return;$('#clock').textContent=V.fmt(S.time);const px=Number($('.timeline')?.dataset.px)||1;if($('#playhead'))$('#playhead').style.left=116+S.time*px+'px';const active=D.active(f(),S.route,S.time);const ids=new Set(active.map(b=>b.id));document.querySelectorAll('.block').forEach(el=>el.classList.toggle('now',ids.has(el.dataset.block)));if($('#now-active'))$('#now-active').innerHTML=active.filter(x=>x.laneId!=='story').slice(0,8).map(x=>`<button data-block="${V.esc(x.id)}">${V.esc(x.laneId)} · ${V.esc(x.label)}</button>`).join('');}
 let last=0;function tick(now){if(S.playing&&f()){if(last)S.time+=(now-last)/1000;if(S.time>=D.duration(f(),S.route)){S.time=D.duration(f(),S.route);S.playing=false;}updateClock();}last=now;requestAnimationFrame(tick);}requestAnimationFrame(tick);
 document.addEventListener('visibilitychange',()=>{S.playing=false;last=0;});
 window.addEventListener('beforeunload',ev=>{if(S.formDirty||S.busy){ev.preventDefault();ev.returnValue='';}});
 let timer;window.addEventListener('resize',()=>{clearTimeout(timer);timer=setTimeout(()=>{if(!S.formDirty&&!drag)render();},200);});
 // Shell upgrades do not replace local project data. Embedded updated projects are adopted only explicitly.
 const embedded=$('#canvastect-data');
 try{if(embedded?.textContent.trim()){const doc=D.normalize(JSON.parse(embedded.textContent));const local=await DB.get(doc.projectId);if(local&&JSON.stringify(local)!==JSON.stringify(doc)){S.doc=local;S.fid=local.fichas[0]?.id;S.pendingImport=doc;render();show(`<h2>Hay una versión local de este proyecto</h2><p>El archivo abierto contiene otra revisión. Puedes conservar la local o adoptar la del archivo guardando primero la anterior en Historial.</p><div class="actions">${V.btn('close','Continuar versión local')}${V.btn('accept-import','Usar archivo y conservar historial','primary')}</div>`);}else await adopt(doc,'Abrir lienzo');}else{let last;try{last=localStorage.getItem('canvastect-last');}catch{}if(last)S.doc=await DB.get(last);render();}}catch(e){render();toast('No se pudo abrir/guardar: '+e.message);}
 // Register only on hosted creator; portable exported HTML never assumes sibling service-worker files.
 if(document.querySelector('meta[name="canvastect-hosted"]')&&'serviceWorker' in navigator&&/^https?:$/.test(location.protocol)){
  navigator.serviceWorker.register('./sw.js').then(reg=>{const offer=()=>{if(reg.waiting)toast('Nueva versión del creador disponible. Recarga después de guardar.');};offer();reg.addEventListener('updatefound',()=>reg.installing?.addEventListener('statechange',offer));}).catch(()=>{});
 }
 // Read-only testing/debug surface; contains no publishing credentials.
 window.CanvastectApp={getDocument:()=>D.clone(S.doc),getState:()=>({fid:S.fid,bid:S.bid,route:S.route}),render};
})();
